# Set color of progress bar. Comma separated RGB decimal values.
PROGRESSBARCOLOR="255,143,0"
# Set size of progress bar. Comma separated decimal values (width, height).
PROGRESSSIZE="600,8"
PROGRESSSIZEHIGH="650,12"
# Set position of progress bar from left,top. Comma separated decimal values.
PROGRESSPOSITION="30,160"
PROGRESSPOSITIONHIGH="30,200"
# Set color of progress bar frame. Comma separated RGB decimal values.
PROGRESSFRAMECOLOR="255,143,0"
# Set color of progress bar text. Comma separated RGB decimal values.
PROGRESSTEXTCOLOR="0,0,0"
# Set vertical position of progress bar text from top. Decimal value.
PROGRESSTEXTBASELINE="190"

